project:
  type: website
  output-dir: docs

website:
  title: "Zaynab's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: cover-letter.qmd
        text: Cover Letter
      - href: project.qmd
        text: Team Project
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/

  page-footer:
    center: "© 2026 Zaynab · Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    toc: false
    page-layout: full
